/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DataAnalysisPanel: typeof import('./src/components/DataAnalysisPanel.vue')['default']
    LoadingBox: typeof import('./src/components/LoadingBox.vue')['default']
    PagePanel: typeof import('./src/components/PagePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SsoAuthPanel: typeof import('./src/components/SsoAuthPanel.vue')['default']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    SystemMonitorDashboard: typeof import('./src/components/SystemMonitorDashboard.vue')['default']
    VoiceInput: typeof import('./src/components/VoiceInput.vue')['default']
  }
}
