"""Deep scan: find hollow modules with stub patterns"""
import os

modules_dir = 'D:\\AUTO-EVO-AI-V0.1\\modules'
archive_dir = os.path.join(modules_dir, '_archive_stub')
os.makedirs(archive_dir, exist_ok=True)

stub_patterns = {
    'empty_handler': ['return None', 'return []', 'return {}', 'return ""', "return ''", 'return False', 'return 0'],
    'not_implemented': ['NotImplementedError', 'raise NotImplementedError'],
    'just_pass': ['pass', 'pass  # TODO'],
    'todo_placeholder': ['TODO:', 'FIXME:', 'HACK:', 'XXX:'],
    'empty_method': ['def _empty', 'def stub', 'def mock'],
    'template_only': ['# This is a', 'Template:', 'generated by AI', 'auto-generated'],
}

# Count patterns
results = []
hollow_count = 0

for f in sorted(os.listdir(modules_dir)):
    if not f.endswith('.py') or f.startswith('_'):
        continue
    fpath = os.path.join(modules_dir, f)
    if os.path.isdir(fpath):
        continue
    try:
        with open(fpath, 'r', encoding='utf-8', errors='replace') as fh:
            content = fh.read()
    except:
        continue
    
    size = os.path.getsize(fpath)
    
    # Check for real imports
    real_imports = [x for x in ['httpx', 'requests', 'sqlalchemy', 'pandas', 'numpy', 'redis', 'boto3', 'minio', 'fastapi', 'paramiko', 'docker', 'kubernetes', 'asyncio'] 
                    if f'import {x}' in content or f'from {x}' in content]
    
    # Check methods
    has_real_method = 'async def' in content or 'def ' in content
    has_assignment = '=' in content
    
    # Stub indicators
    # Check if all defs just return None/empty or pass
    lines = content.split('\n')
    def_blocks = []
    in_def = False
    current_block = []
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith('def ') or stripped.startswith('async def '):
            if current_block and in_def:
                def_blocks.append(current_block)
            current_block = [stripped]
            in_def = True
        elif in_def:
            if stripped.startswith('def ') or stripped.startswith('class ') or stripped.startswith('@'):
                def_blocks.append(current_block)
                if stripped.startswith('def ') or stripped.startswith('async def '):
                    current_block = [stripped]
                else:
                    in_def = False
                    current_block = []
            elif stripped:
                current_block.append(stripped)
            elif not stripped:
                pass
    
    if current_block and in_def:
        def_blocks.append(current_block)
    
    hollow_defs = 0
    total_defs = len(def_blocks)
    for block in def_blocks:
        body = '\n'.join(block)
        # Check if body only has: pass, return None, docstring, comments
        body_lines = [l for l in block[1:] if l.strip() and not l.strip().startswith('#') and not l.strip().startswith(('"""', "'''")) and not l.strip() == '...']
        if len(body_lines) == 0:
            hollow_defs += 1
        elif all(l.strip() in ['pass', 'return None', 'return []', 'return {}', 'return ""', "return ''", 'return False', 'return 0', '...'] for l in body_lines):
            hollow_defs += 1
        elif len(body_lines) == 1 and any(x in body_lines[0] for x in ['NotImplementedError', 'return None', 'return []']):
            hollow_defs += 1
    
    hollow_pct = (hollow_defs / total_defs * 100) if total_defs > 0 else 0
    
    if total_defs > 0 and hollow_pct >= 70:
        hollow_count += 1
        results.append((f, size, total_defs, hollow_defs, hollow_pct, ','.join(real_imports)))

# Sort by hollow percentage descending
results.sort(key=lambda x: -x[4])

print(f'=== HOLLOW MODULE REPORT ===')
print(f'Modules with >=70% hollow defs: {hollow_count}')
print()
print(f'{"File":45s} {"Size":>6s} {"Defs":>5s} {"Hollow":>6s} {"%":>5s} {"Real Imports":20s}')
print('-' * 100)
for f, size, total, hollow, pct, imps in results:
    imps_short = imps[:18] if imps else '(none)'
    print(f'{f:45s} {size:>6}B {total:>5d} {hollow:>6d} {pct:>4.0f}% {imps_short:20s}')
