#!/usr/bin/env python3
import paramiko, time
C=paramiko.SSHClient()
C.set_missing_host_key_policy(paramiko.AutoAddPolicy())
C.connect('122.51.144.227',port=22,username='ubuntu',password='Hj711201',timeout=10,banner_timeout=60)
time.sleep(15)
_,o,_=C.exec_command("sudo systemctl is-active evo.service",timeout=10,get_pty=True)
s=o.read().decode().strip()
print(f"状态: {s}")
if s=='active':
    _,r1,_=C.exec_command('curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8765/api/v1/hub/discover',timeout=10,get_pty=True)
    print(f"Hub: {r1.read().decode().strip()}")
    _,r2,_=C.exec_command('curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8765/api/v1/company/status',timeout=10,get_pty=True)
    print(f"Company: {r2.read().decode().strip()}")
    _,r3,_=C.exec_command('curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8765/hub',timeout=10,get_pty=True)
    print(f"HubPage: {r3.read().decode().strip()}")
    _,r4,_=C.exec_command('curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8765/company',timeout=10,get_pty=True)
    print(f"CompanyPage: {r4.read().decode().strip()}")
    _,r5,_=C.exec_command('curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8765/canvas',timeout=10,get_pty=True)
    print(f"Canvas: {r5.read().decode().strip()}")
    _,r6,_=C.exec_command('curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8765/fork',timeout=10,get_pty=True)
    print(f"Fork: {r6.read().decode().strip()}")
else:
    _,e,_=C.exec_command("sudo journalctl -u evo --no-pager -n 15 2>/dev/null|grep -i 'error\\|traceback'|tail -5",timeout=10,get_pty=True)
    print(f"错误: {e.read().decode()[:500]}")
C.close()
