import paramiko
C=paramiko.SSHClient()
C.set_missing_host_key_policy(paramiko.AutoAddPolicy())
C.connect('122.51.144.227',port=22,username='ubuntu',password='Hj711201',timeout=10,banner_timeout=60)
_,o,_=C.exec_command("sudo journalctl -u evo -n 30 --no-pager 2>/dev/null|grep -i 'error\\|traceback\\|syntax\\|import\\|No module'|tail -10",timeout=15,get_pty=True)
print(o.read().decode()[:800])
_,o2,_=C.exec_command("head -6 /home/ubuntu/my-evo-ai/api/hub/integrate.py",timeout=10,get_pty=True)
print('\n---integrate.py 前6行---')
print(o2.read().decode()[:300])
C.close()
