"""Agent 工具定义 — 从 agent_core.py get_tools() 中分离出来的纯数据层

所有工具按 OpenAI function calling 格式定义，供 agent_core 引用。
此文件不含业务逻辑，只含数据。
"""

BUILTIN_TOOLS = [
    # ===== 基础工具 =====
    {"type":"function","function":{"name":"read_file","description":"读取任意文件","parameters":{"type":"object","properties":{"path":{"type":"string"}},"required":["path"]}}},
    {"type":"function","function":{"name":"list_modules","description":"列出系统所有模块","parameters":{"type":"object","properties":{}}}},
    {"type":"function","function":{"name":"search_modules","description":"按中文关键词搜索模块","parameters":{"type":"object","properties":{"keyword":{"type":"string"}},"required":["keyword"]}}},
    {"type":"function","function":{"name":"module_info","description":"查看模块详细信息","parameters":{"type":"object","properties":{"module":{"type":"string"}},"required":["module"]}}},
    {"type":"function","function":{"name":"get_module_demo","description":"获取模块调用示例","parameters":{"type":"object","properties":{"module":{"type":"string"}},"required":["module"]}}},
    {"type":"function","function":{"name":"execute_module","description":"调用系统模块执行任务","parameters":{"type":"object","properties":{"module":{"type":"string"},"action":{"type":"string"},"params":{"type":"string"}},"required":["module","action"]}}},
    {"type":"function","function":{"name":"file_write","description":"写文件","parameters":{"type":"object","properties":{"name":{"type":"string"},"content":{"type":"string"},"type":{"type":"string","enum":["html","python","text","json","tool"]}},"required":["name","content"]}}},
    {"type":"function","function":{"name":"register_tool","description":"注册.py为工具","parameters":{"type":"object","properties":{"name":{"type":"string"},"filepath":{"type":"string"}},"required":["name","filepath"]}}},
    {"type":"function","function":{"name":"create_task","description":"创建定时任务","parameters":{"type":"object","properties":{"name":{"type":"string"},"schedule":{"type":"string"},"action":{"type":"string"},"params":{"type":"string"}},"required":["name","schedule","action"]}}},
    {"type":"function","function":{"name":"list_tools","description":"列出所有工具","parameters":{"type":"object","properties":{}}}},
    {"type":"function","function":{"name":"draw_image","description":"AI画图","parameters":{"type":"object","properties":{"prompt":{"type":"string"}},"required":["prompt"]}}},
    {"type":"function","function":{"name":"web_search","description":"搜索信息","parameters":{"type":"object","properties":{"query":{"type":"string"}},"required":["query"]}}},

    # ===== 2026-06-08 新增集成工具 =====
    {"type":"function","function":{"name":"browser_use_task","description":"浏览器自动化：AI自动操控浏览器完成登录/填表/抓取/发帖等任务","parameters":{"type":"object","properties":{"task":{"type":"string"}},"required":["task"]}}},
    {"type":"function","function":{"name":"gpt_research","description":"自主研究：自动搜索→抓取→生成带引用的研究报告","parameters":{"type":"object","properties":{"query":{"type":"string"}},"required":["query"]}}},
    {"type":"function","function":{"name":"openhands_generate","description":"全栈项目生成：生成前端+后端+数据库+测试的完整项目","parameters":{"type":"object","properties":{"description":{"type":"string"},"project_type":{"type":"string"}},"required":["description"]}}},
    {"type":"function","function":{"name":"letta_message","description":"Letta记忆：发送消息到操作系统级记忆系统","parameters":{"type":"object","properties":{"message":{"type":"string"}},"required":["message"]}}},
    {"type":"function","function":{"name":"composio_execute","description":"Composio工具：执行200+外部工具（GitHub/Slack/Gmail等）","parameters":{"type":"object","properties":{"app_name":{"type":"string"},"action_name":{"type":"string"},"params":{"type":"string"}},"required":["app_name","action_name"]}}},
    {"type":"function","function":{"name":"self_evolving_analyze","description":"自进化分析：分析代码库，找出潜在改进点","parameters":{"type":"object","properties":{"repo_path":{"type":"string"}}}}},
    {"type":"function","function":{"name":"moltron_learn","description":"Moltron技能学习：学习新技能并写入Skills.md","parameters":{"type":"object","properties":{"skill_name":{"type":"string"},"skill_description":{"type":"string"}},"required":["skill_name","skill_description"]}}},
    {"type":"function","function":{"name":"accomplish_desktop","description":"桌面自动化：执行桌面自动化工作流","parameters":{"type":"object","properties":{"workflow":{"type":"string"}}}}},
    {"type":"function","function":{"name":"toolbench_discover","description":"ToolBench API发现：从12万+API注册表中搜索可调用的外部API","parameters":{"type":"object","properties":{"query":{"type":"string"},"category":{"type":"string"},"action":{"type":"string"},"api_name":{"type":"string"}}}}},

    # ===== 2026-06-09 新增16个集成工具 =====
    {"type":"function","function":{"name":"markitdown_convert","description":"文档转Markdown：将PDF/Word/Excel/PPT/图片转为Markdown","parameters":{"type":"object","properties":{"file_path":{"type":"string"},"text":{"type":"string"},"file_type":{"type":"string"}}}}},
    {"type":"function","function":{"name":"scrapegraphai_scrape","description":"AI智能爬虫：一句话让AI自动爬取网页结构化数据","parameters":{"type":"object","properties":{"url":{"type":"string"},"prompt":{"type":"string"}},"required":["url"]}}},
    {"type":"function","function":{"name":"interpreter_execute","description":"电脑控制：用自然语言控制电脑（读写文件/运行代码）","parameters":{"type":"object","properties":{"command":{"type":"string"},"language":{"type":"string"}},"required":["command"]}}},
    {"type":"function","function":{"name":"s2c_generate","description":"截图转代码：上传截图直接生成前端代码","parameters":{"type":"object","properties":{"image_path":{"type":"string"},"image_url":{"type":"string"},"stack":{"type":"string"}}}}},
    {"type":"function","function":{"name":"pra_review","description":"PR代码审查：AI自动审查GitHub PR","parameters":{"type":"object","properties":{"pr_url":{"type":"string"},"repo":{"type":"string"},"pr_number":{"type":"integer"}}}}},
    {"type":"function","function":{"name":"qodo_testgen","description":"自动生成测试：给源码自动生成单元测试","parameters":{"type":"object","properties":{"source_path":{"type":"string"},"source_code":{"type":"string"},"framework":{"type":"string"}}}}},
    {"type":"function","function":{"name":"aider_edit","description":"AI代码编辑：自然语言描述→自动修改代码文件","parameters":{"type":"object","properties":{"file_path":{"type":"string"},"instruction":{"type":"string"}},"required":["file_path","instruction"]}}},
    {"type":"function","function":{"name":"openclaw_connect","description":"消息平台桥接：连接OpenClaw到Telegram/WhatsApp等20+平台","parameters":{"type":"object","properties":{"platform":{"type":"string"},"bot_token":{"type":"string"}},"required":["platform"]}}},
    {"type":"function","function":{"name":"openclaw_send","description":"发送消息：通过已桥接的OpenClaw平台发送消息","parameters":{"type":"object","properties":{"platform":{"type":"string"},"recipient":{"type":"string"},"message":{"type":"string"}},"required":["platform","recipient","message"]}}},
    {"type":"function","function":{"name":"tts_speak","description":"语音合成：文本转语音","parameters":{"type":"object","properties":{"text":{"type":"string"},"voice":{"type":"string"},"emotion":{"type":"string"}},"required":["text"]}}},
    {"type":"function","function":{"name":"chatdev_run","description":"ChatDev多智能体：自动组建智能体团队完成任务","parameters":{"type":"object","properties":{"task":{"type":"string"}},"required":["task"]}}},
    {"type":"function","function":{"name":"openmanus_run","description":"OpenManus通用Agent：运行通用AI Agent任务","parameters":{"type":"object","properties":{"task":{"type":"string"}},"required":["task"]}}},
    {"type":"function","function":{"name":"autogpt_run","description":"AutoGPT自主Agent：长期自主执行任务（计划→执行→评估循环）","parameters":{"type":"object","properties":{"goal":{"type":"string"},"max_steps":{"type":"integer"}},"required":["goal"]}}},
    {"type":"function","function":{"name":"agenteval_benchmark","description":"Agent评测：自动评测Agent性能","parameters":{"type":"object","properties":{}}}},
    {"type":"function","function":{"name":"swe_fix","description":"SWE-agent：自动分析和修复GitHub Issue","parameters":{"type":"object","properties":{"repo":{"type":"string"},"issue_number":{"type":"integer"}},"required":["repo","issue_number"]}}},
    {"type":"function","function":{"name":"gptpilot_build","description":"GPT-Pilot：从需求生成完整项目","parameters":{"type":"object","properties":{"description":{"type":"string"}},"required":["description"]}}},
    {"type":"function","function":{"name":"text2sql_query","description":"自然语言查数据库：用中文查数据库出结果","parameters":{"type":"object","properties":{"question":{"type":"string"},"connection":{"type":"string"}},"required":["question"]}}},
    {"type":"function","function":{"name":"bolt_generate","description":"Bolt.new：一句话生成完整Web应用","parameters":{"type":"object","properties":{"prompt":{"type":"string"},"framework":{"type":"string"}},"required":["prompt"]}}},
    {"type":"function","function":{"name":"agentk8s_deploy","description":"K8s部署：生成Agent的Kubernetes部署清单","parameters":{"type":"object","properties":{"agent_name":{"type":"string"}}}}},

    # ===== 2026-06-09 第3轮 22个集成工具 =====
    {"type":"function","function":{"name":"openmontage_generate_script","description":"视频脚本生成：OpenMontage AI视频制作脚本生成","parameters":{"type":"object","properties":{"topic":{"type":"string"},"style":{"type":"string"},"duration":{"type":"integer"}},"required":["topic"]}}},
    {"type":"function","function":{"name":"openmontage_search_materials","description":"视频素材搜索：搜索OpenMontage可用视频素材","parameters":{"type":"object","properties":{"keywords":{"type":"string"}},"required":["keywords"]}}},
    {"type":"function","function":{"name":"lida_visualize","description":"LIDA数据可视化：自然语言描述→自动生成图表","parameters":{"type":"object","properties":{"data_description":{"type":"string"},"goal":{"type":"string"},"chart_type":{"type":"string"}},"required":["data_description","goal"]}}},
    {"type":"function","function":{"name":"lida_explore","description":"探索性数据分析：自动分析CSV出多角度图表","parameters":{"type":"object","properties":{"data_file_path":{"type":"string"}},"required":["data_file_path"]}}},
    {"type":"function","function":{"name":"paddleocr_image","description":"OCR图片文字识别：从图片中提取文字（支持中英文）","parameters":{"type":"object","properties":{"image_path":{"type":"string"},"lang":{"type":"string"}},"required":["image_path"]}}},
    {"type":"function","function":{"name":"paddleocr_pdf","description":"OCR PDF识别：从PDF中提取文字（逐页）","parameters":{"type":"object","properties":{"pdf_path":{"type":"string"}},"required":["pdf_path"]}}},
    {"type":"function","function":{"name":"zen_scan","description":"安全漏洞扫描：对目标进行安全扫描发现潜在风险","parameters":{"type":"object","properties":{"target":{"type":"string"},"scan_type":{"type":"string"}},"required":["target"]}}},
    {"type":"function","function":{"name":"zen_report","description":"安全报告生成：生成安全评估总结报告","parameters":{"type":"object","properties":{"target":{"type":"string"}},"required":["target"]}}},
    {"type":"function","function":{"name":"shannon_audit","description":"代码安全审计：用Semgrep自动审计源码安全漏洞","parameters":{"type":"object","properties":{"source_path":{"type":"string"}},"required":["source_path"]}}},
    {"type":"function","function":{"name":"openant_scan","description":"LLM驱动的Web安全扫描（Headers/Cookie/HSTS检查）","parameters":{"type":"object","properties":{"target":{"type":"string"}},"required":["target"]}}},
    {"type":"function","function":{"name":"legal_review_contract","description":"合同条款审查：AI自动审查合同条款","parameters":{"type":"object","properties":{"contract_text":{"type":"string"}},"required":["contract_text"]}}},
    {"type":"function","function":{"name":"legal_analyze_compliance","description":"合规性分析：检查文档是否符合法规要求","parameters":{"type":"object","properties":{"document_text":{"type":"string"},"standard":{"type":"string"}},"required":["document_text"]}}},
    {"type":"function","function":{"name":"twenty_create_contact","description":"CRM创建联系人","parameters":{"type":"object","properties":{"name":{"type":"string"},"email":{"type":"string"}},"required":["name"]}}},
    {"type":"function","function":{"name":"twenty_create_deal","description":"CRM创建交易","parameters":{"type":"object","properties":{"name":{"type":"string"},"amount":{"type":"number"}},"required":["name","amount"]}}},
    {"type":"function","function":{"name":"frappe_hr_employee","description":"HR员工查询","parameters":{"type":"object","properties":{"employee_id":{"type":"string"}},"required":["employee_id"]}}},
    {"type":"function","function":{"name":"frappe_hr_leave","description":"HR请假申请","parameters":{"type":"object","properties":{"employee_id":{"type":"string"},"start_date":{"type":"string"},"end_date":{"type":"string"}},"required":["employee_id","start_date","end_date"]}}},
    {"type":"function","function":{"name":"invoice_create","description":"创建发票","parameters":{"type":"object","properties":{"client":{"type":"string"},"amount":{"type":"number"}},"required":["client","amount"]}}},
    {"type":"function","function":{"name":"invoice_track_expense","description":"记录费用","parameters":{"type":"object","properties":{"description":{"type":"string"},"amount":{"type":"number"}},"required":["description","amount"]}}},
    {"type":"function","function":{"name":"chatwoot_create_ticket","description":"创建客服工单","parameters":{"type":"object","properties":{"subject":{"type":"string"},"description":{"type":"string"},"customer_email":{"type":"string"}},"required":["subject"]}}},
    {"type":"function","function":{"name":"chatwoot_reply_ticket","description":"回复工单","parameters":{"type":"object","properties":{"ticket_id":{"type":"string"},"message":{"type":"string"}},"required":["ticket_id","message"]}}},
    {"type":"function","function":{"name":"postiz_create_post","description":"社交媒体发帖","parameters":{"type":"object","properties":{"content":{"type":"string"},"platforms":{"type":"string"}},"required":["content"]}}},
    {"type":"function","function":{"name":"mautic_send_email","description":"营销邮件发送","parameters":{"type":"object","properties":{"subject":{"type":"string"},"content":{"type":"string"}},"required":["subject","content"]}}},
    {"type":"function","function":{"name":"superset_create_chart","description":"Superset图表创建","parameters":{"type":"object","properties":{"dataset":{"type":"string"},"chart_type":{"type":"string"}},"required":["dataset"]}}},
    {"type":"function","function":{"name":"dataease_create_dashboard","description":"DataEase仪表盘创建","parameters":{"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}}},
    {"type":"function","function":{"name":"heyform_create_survey","description":"创建问卷调查","parameters":{"type":"object","properties":{"title":{"type":"string"}},"required":["title"]}}},
    {"type":"function","function":{"name":"docetl_extract","description":"文档ETL提取","parameters":{"type":"object","properties":{"file_paths":{"type":"string"}},"required":["file_paths"]}}},
    {"type":"function","function":{"name":"accord_create_contract","description":"创建法律协议/合同","parameters":{"type":"object","properties":{"template":{"type":"string"}},"required":["template"]}}},
    {"type":"function","function":{"name":"claude_code_generate","description":"Claude Code生成代码","parameters":{"type":"object","properties":{"prompt":{"type":"string"},"language":{"type":"string"}},"required":["prompt"]}}},

    # ===== 2026-06-09 第4轮 21个基础设施工具 =====
    {"type":"function","function":{"name":"plane_project","description":"项目管理：创建/管理项目（开源Jira替代）","parameters":{"type":"object","properties":{"name":{"type":"string"},"description":{"type":"string"}},"required":["name"]}}},
    {"type":"function","function":{"name":"openproject_mgmt","description":"企业项目管理：甘特图/成本/工时管理","parameters":{"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}}},
    {"type":"function","function":{"name":"cal_schedule","description":"日程调度：Cal.com自动安排会议/预订","parameters":{"type":"object","properties":{"title":{"type":"string"},"duration":{"type":"integer"},"invitees":{"type":"string"}},"required":["title"]}}},
    {"type":"function","function":{"name":"novu_notify","description":"统一通知：通过Novu发送Email/SMS/推送通知","parameters":{"type":"object","properties":{"channel":{"type":"string"},"to":{"type":"string"},"content":{"type":"string"}},"required":["channel","to","content"]}}},
    {"type":"function","function":{"name":"keycloak_auth","description":"身份认证：Keycloak用户认证/SSO登录","parameters":{"type":"object","properties":{"username":{"type":"string"},"password":{"type":"string"}},"required":["username","password"]}}},
    {"type":"function","function":{"name":"meilisearch_search","description":"全文搜索：Meilisearch毫秒级搜索（支持中文）","parameters":{"type":"object","properties":{"query":{"type":"string"},"index":{"type":"string"}},"required":["query"]}}},
    {"type":"function","function":{"name":"minio_storage","description":"对象存储：MinIO S3文件管理","parameters":{"type":"object","properties":{"action":{"type":"string"},"bucket":{"type":"string"},"file_path":{"type":"string"}},"required":["action","bucket"]}}},
    {"type":"function","function":{"name":"opentofu_apply","description":"IaC基础设施：OpenTofu声明式云资源管理","parameters":{"type":"object","properties":{"config":{"type":"string"}},"required":["config"]}}},
    {"type":"function","function":{"name":"ansible_run","description":"配置管理：Ansible Playbook生成执行","parameters":{"type":"object","properties":{"playbook":{"type":"string"},"inventory":{"type":"string"}},"required":["playbook"]}}},
    {"type":"function","function":{"name":"strapi_cms","description":"CMS内容管理：Strapi Headless CMS","parameters":{"type":"object","properties":{"content_type":{"type":"string"},"data":{"type":"string"}},"required":["content_type","data"]}}},
    {"type":"function","function":{"name":"directus_api","description":"数据平台：Directus自动为SQL生成API","parameters":{"type":"object","properties":{"collection":{"type":"string"}},"required":["collection"]}}},
    {"type":"function","function":{"name":"uptime_kuma","description":"站点监控：Uptime Kuma监控站点状态（80+协议）","parameters":{"type":"object","properties":{"target":{"type":"string"},"type":{"type":"string"}},"required":["target"]}}},
    {"type":"function","function":{"name":"oneuptime_monitor","description":"一体化可观测：OneUptime监控+告警+事件","parameters":{"type":"object","properties":{"monitor_type":{"type":"string"}},"required":["monitor_type"]}}},
    {"type":"function","function":{"name":"signoz_apm","description":"APM性能监控：SigNoz追踪+指标+日志","parameters":{"type":"object","properties":{"service":{"type":"string"}},"required":["service"]}}},
    {"type":"function","function":{"name":"wazuh_siem","description":"安全监控：Wazuh SIEM/XDR入侵检测","parameters":{"type":"object","properties":{"action":{"type":"string"}},"required":["action"]}}},
    {"type":"function","function":{"name":"nats_mq","description":"消息队列：NATS轻量级事件总线","parameters":{"type":"object","properties":{"subject":{"type":"string"},"message":{"type":"string"}},"required":["subject","message"]}}},
    {"type":"function","function":{"name":"rabbitmq_broker","description":"消息代理：RabbitMQ企业级消息管理","parameters":{"type":"object","properties":{"action":{"type":"string"},"queue":{"type":"string"},"message":{"type":"string"}},"required":["action","queue"]}}},
    {"type":"function","function":{"name":"gitea_git","description":"Git仓库管理：Gitea自托管Git仓库/PR/CI/CD","parameters":{"type":"object","properties":{"action":{"type":"string"},"repo":{"type":"string"}},"required":["action","repo"]}}},
    {"type":"function","function":{"name":"wikijs_wiki","description":"Wiki知识管理：Wiki.js创建/编辑页面","parameters":{"type":"object","properties":{"title":{"type":"string"},"content":{"type":"string"}},"required":["title","content"]}}},
    {"type":"function","function":{"name":"bookstack_wiki","description":"文档系统：BookStack书架→章节→页面管理","parameters":{"type":"object","properties":{"action":{"type":"string"},"name":{"type":"string"},"content":{"type":"string"}},"required":["action","name"]}}},
    {"type":"function","function":{"name":"projectsend_files","description":"安全文件共享：ProjectSend上传/分享文件","parameters":{"type":"object","properties":{"action":{"type":"string"},"file_path":{"type":"string"}},"required":["action"]}}},

    # ===== 第5轮 20个企业纵深自动化工具（之前遗漏，现在补上）=====
    {"type":"function","function":{"name":"odoo_manage","description":"Odoo ERP：管理会计/库存/采购/销售/制造/HR模块","parameters":{"type":"object","properties":{"module":{"type":"string"},"action":{"type":"string"}},"required":["module"]}}},
    {"type":"function","function":{"name":"erpclaw_manage","description":"ERPClaw AI-ERP：14行业46模块AI原生ERP","parameters":{"type":"object","properties":{"module":{"type":"string"},"industry":{"type":"string"}},"required":["module","industry"]}}},
    {"type":"function","function":{"name":"coolify_deploy","description":"Coolify PaaS：自托管部署应用和数据库","parameters":{"type":"object","properties":{"app_name":{"type":"string"},"action":{"type":"string"}},"required":["app_name"]}}},
    {"type":"function","function":{"name":"rustdesk_connect","description":"RustDesk远程桌面：远程控制电脑","parameters":{"type":"object","properties":{"target":{"type":"string"},"action":{"type":"string"}},"required":["target"]}}},
    {"type":"function","function":{"name":"docuseal_sign","description":"DocuSeal电子签名：在线文档签署","parameters":{"type":"object","properties":{"document":{"type":"string"},"signers":{"type":"string"}},"required":["document","signers"]}}},
    {"type":"function","function":{"name":"homeassistant_control","description":"智能家居：控制IoT设备/灯光/传感器/自动化场景","parameters":{"type":"object","properties":{"device":{"type":"string"},"action":{"type":"string"},"state":{"type":"string"}},"required":["device"]}}},
    {"type":"function","function":{"name":"vaultwarden_manage","description":"密码管理：安全存储和检索密码凭证","parameters":{"type":"object","properties":{"action":{"type":"string"},"site":{"type":"string"}},"required":["site"]}}},
    {"type":"function","function":{"name":"nocodb_manage","description":"NocoDB数据表：数据库→电子表格可视化管理","parameters":{"type":"object","properties":{"table":{"type":"string"},"action":{"type":"string"}},"required":["table"]}}},
    {"type":"function","function":{"name":"appsmith_build","description":"Appsmith低代码：拖拽式构建内部管理工具","parameters":{"type":"object","properties":{"app_name":{"type":"string"},"action":{"type":"string"}},"required":["app_name"]}}},
    {"type":"function","function":{"name":"airbyte_sync","description":"Airbyte ETL：数据采集/清洗/同步管道","parameters":{"type":"object","properties":{"source":{"type":"string"},"destination":{"type":"string"},"action":{"type":"string"}},"required":["source","destination"]}}},
    {"type":"function","function":{"name":"mlflow_track","description":"MLflow MLOps：AI模型训练/部署/追踪","parameters":{"type":"object","properties":{"experiment":{"type":"string"},"action":{"type":"string"}},"required":["experiment"]}}},
    {"type":"function","function":{"name":"langfuse_observe","description":"Langfuse LLM可观测：Prompt管理/评估/追踪","parameters":{"type":"object","properties":{"action":{"type":"string"},"project":{"type":"string"}},"required":["project"]}}},
    {"type":"function","function":{"name":"hoppscotch_test","description":"Hoppscotch API测试：API调试/Mock/回归测试","parameters":{"type":"object","properties":{"endpoint":{"type":"string"},"method":{"type":"string"},"body":{"type":"string"}},"required":["endpoint","method"]}}},
    {"type":"function","function":{"name":"grist_analyze","description":"Grist电子表格：关系型数据分析/Python公式","parameters":{"type":"object","properties":{"table":{"type":"string"},"action":{"type":"string"}},"required":["table"]}}},
    {"type":"function","function":{"name":"freshrss_read","description":"FreshRSS聚合：RSS订阅/信息采集/资讯监控","parameters":{"type":"object","properties":{"action":{"type":"string"},"feed":{"type":"string"}},"required":["feed"]}}},
    {"type":"function","function":{"name":"listmonk_send","description":"Listmonk邮件：邮件列表/Newsletter/营销邮件","parameters":{"type":"object","properties":{"action":{"type":"string"},"list_id":{"type":"string"}},"required":["list_id"]}}},
    {"type":"function","function":{"name":"mermaid_chart","description":"Mermaid图表：文本→流程图/架构图/时序图","parameters":{"type":"object","properties":{"chart_type":{"type":"string"},"description":{"type":"string"}},"required":["chart_type"]}}},
    {"type":"function","function":{"name":"nocobase_build","description":"NocoBase低代码：AI+低代码快速构建业务应用","parameters":{"type":"object","properties":{"app_name":{"type":"string"},"action":{"type":"string"}},"required":["app_name"]}}},
    {"type":"function","function":{"name":"scriberr_transcribe","description":"音频转录：AI将音频/会议转录为文字","parameters":{"type":"object","properties":{"audio_path":{"type":"string"},"action":{"type":"string"}},"required":["audio_path"]}}},
    {"type":"function","function":{"name":"keploy_test","description":"Keploy AI测试：自动生成API回归测试","parameters":{"type":"object","properties":{"action":{"type":"string"},"endpoint":{"type":"string"}},"required":["endpoint"]}}},

    # ===== 并发多Agent + 自进化 =====
    {"type":"function","function":{"name":"concurrent_run","description":"并发多Agent：同时运行多个Agent并行协作完成任务","parameters":{"type":"object","properties":{"task_name":{"type":"string"},"details":{"type":"string"},"mode":{"type":"string"}},"required":["task_name"]}}},
    {"type":"function","function":{"name":"yoyo_scan","description":"自进化扫描：自动分析代码库质量和潜在改进点","parameters":{"type":"object","properties":{"scope":{"type":"string"}},"required":[]}}},
    {"type":"function","function":{"name":"yoyo_history","description":"自进化历史：查看自进化系统的优化记录","parameters":{"type":"object","properties":{"limit":{"type":"integer"}},"required":[]}}},
]
